### ISSUE TITLE
isFinite global function is available since ES3

### ISSUE THREAD

**Issue by vvo** [sindresorhus/is-finite#3]
Reading https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isFinite, it seems the global isFinite function is available since ES3 (so basically every browser currently used in the world).

Can you precise what was the motivation to right your module? Thanks.

**Comment by sindresorhus** [comment]
If you read the readme again, you'll see that this is not a ponyfill for the global method ;)

**Comment by vvo** [comment]
Yep I re-read again and found out then on MDN that isFinite and Number.isFinite have different implementations (isFinite accepts strings)
