### ISSUE TITLE
This is a polyfill as opposed to a ponyfill

### ISSUE THREAD

**Issue by xenyal** [sindresorhus/is-finite#4]
In https://github.com/sindresorhus/ponyfill, it says that the distinction between polyfill and ponyfill is that the former falls back from the native implementation should it not exist, and use some fallback function. In the case of this library, that seems to still hold true.

I can make a PR to update the README.md to reflect that if you're ok with that

**Comment by kevva** [comment]
This is a ponyfill in the sense that it doesn't patch any globals. However, as stated in https://github.com/sindresorhus/ponyfill, it shouldn't use the native API either which we're doing here https://github.com/sindresorhus/is-finite/blob/master/index.js#L4.

> Ponyfills should never use the native API, even if available, as it might have slightly different behavior between environments, which can cause bugs.

**Comment by xenyal** [comment]
Ahh touche!
